### ISSUE TITLE
Splunk Integration

### ISSUE THREAD

**Issue by calebhailey** [sensu-community/monitoring-pipelines#42]
Add a template for leveraging a Sensu Go socket handler to send Sensu events to a Splunk Universal Forwarder via TCP socket. 

Note: no plugin is required for this template. 

References:  
- https://docs.splunk.com/Documentation/Forwarder/8.0.4/Forwarder/Abouttheuniversalforwarder 
- https://docs.sensu.io/sensu-go/latest/reference/handlers/#tcpudp-handlers

**Comment by nixwiz** [comment]
Initial attempt was merged in #44 , is this sufficient or are we looking to have others use this as a base to expand upon?

**Comment by calebhailey** [comment]
I think #44 did the trick for now. 👍
